source 'https://rubygems.org'

gem 'sinatra'
gem 'sinatra-json'
gem 'sinatra-param'
gem 'sinatra-contrib'
gem 'activesupport'
gem 'nokogiri', '~> 1.8'
gem 'rack-protection', '~> 1.5'

gem 'limitless-led'
gem 'ledenet_api', '>= 1.0.0'
gem 'color'
gem 'easy_upnp', '>= 1.1.12'
gem 'oauth2'
gem 'mqtt'

gem 'bravtroller', '~> 1.0'
gem 'net-ping'
gem 'puma'

gem 'crack'
gem 'ruby-enum'
gem 'ruby-pcap'
gem 'thread'
